EC-CUBE/Eccube-Styleguide

- assets/scss/component/3.2.inputMisc.scss
- assets/tmpl/elements/19.1.register.pug
close #41 
- パスワード入力時、●にする
- 性別テキスト太字を標準へ変更
変更完了
> マイページ　会員情報編集

- assets/tmpl/elements/9.1.mypage.pug
> マイページ　お気に入り一覧

- assets/scss/component/5.2.layout.scss
- assets/scss/project/16.1.history.scss
- assets/tmpl/elements/16.1.history.pug
close #39 
画像サイズ等変更しました。
他で使われている場合挙動がおかしくなる可能性があるのでレビューお願いします。
> マイページ　ご注文履歴

- assets/scss/component/3.2.inputMisc.scss
- assets/scss/component/5.2.layout.scss
- assets/scss/component/7.3.cart.scss
- assets/scss/project/15.2.order.scss
- assets/tmpl/elements/15.2.order.pug
レスポンシブ対応　close #53
http://demo3.ec-cube.net/shopping
※商品をカートに入れた後、確認画面まで進む必要あり
http://eccube3-styleguide.herokuapp.com/moc/guest/cart5/
> ご注文内容のご確認ページ #53

- README.md
- app.json
- assets/scss/component/1.1.heading.scss
- assets/scss/component/1.3.list.scss
- assets/scss/component/3.1.inputText.scss
- assets/scss/component/3.2.inputMisc.scss
- assets/scss/component/5.1.grid.scss
- assets/scss/component/5.2.layout.scss
- assets/scss/component/6.3.login.scss
- assets/scss/component/7.1.itembanner.scss
- assets/scss/component/7.3.cart.scss
- assets/scss/component/9.1.mypage.scss
- assets/scss/mixins/media.scss
- assets/scss/project/11.1.role.scss
- assets/scss/project/11.2.header.scss
- assets/scss/project/15.1.cart.scss
- assets/scss/project/15.2.order.scss
- assets/scss/project/16.1.history.scss
- assets/tmpl/elements/11.2.header.pug
- assets/tmpl/elements/15.2.order.pug
- assets/tmpl/elements/16.1.history.pug
- assets/tmpl/elements/6.3.login.pug
- assets/tmpl/elements/9.1.mypage.pug
- assets/tmpl/moc/guest/cart5/index.pug
- assets/tmpl/moc/guest/login/error/index.pug
- assets/tmpl/moc/user/_layout.pug
- assets/tmpl/moc/user/favorite/index.pug
colse #61
- マイページ用のコンテナを設定
- レスポンシブ対応
- アイテムが複数ある場合のレイアウト調整
> マイページ/お気に入り一覧（お気に入り登録あり） #61

- assets/tmpl/elements/9.1.mypage.pug
- assets/tmpl/moc/user/favorite/empty/index.pug
close #64 
- マイページ用のコンテナ適用
- sp対応
> 【moc】マイページ/お気に入り一覧（お気に入り登録なし）#64

- assets/scss/project/21.1.withdraw.scss
> マイページ　退会手続き

- assets/tmpl/moc/user/address/new/error/index.pug
> お届け先登録　moc修正　未完成

- assets/scss/project/12.2.eyecatch.scss
issue #29 対応。
- TOPの全体の余白が同じになるよう調整。
- 画面幅が変わった場合も同調して可変するように修正。
> issue #29 TOPの全体の余白が同じになるよう調整。画面幅が変わった場合も同調して可変するように修正。

- assets/scss/component/7.2.search.scss
- assets/scss/component/7.3.cart.scss
issue #72 スタイルガイドの【７商品】トピックパス、総計の下線がつかないように修正
> issue #72 トピックパス、総計の下線がつかないように修正

- assets/scss/component/3.1.inputText.scss
- assets/scss/component/6.3.login.scss
- assets/tmpl/elements/17.1.address.pug
- assets/tmpl/elements/19.1.register.pug
- assets/tmpl/elements/19.2.contact.pug
- assets/tmpl/elements/19.3.customer.pug
- assets/tmpl/elements/6.3.login.pug
- assets/tmpl/elements/9.1.mypage.pug
Issue #114 対応
- エラーメッセージのコンポーネントのクラスを.ec-errorMessageで統一
- お届け先の編集　一部マークアップ修正
> issue #114 対応

- assets/tmpl/elements/9.1.mypage.pug
- assets/tmpl/moc/user/favorite/index.pug
> #151 サンプルを２つ表示に変更

- assets/tmpl/elements/15.2.order.pug
- assets/tmpl/moc/guest/cart4/error/index.pug
> #153 マークアップ修正

- assets/scss/project/15.1.cart.scss
- assets/tmpl/elements/15.1.cart.pug
> #147 スタイルガイド追加　商品マイナスボタン無効化

- assets/scss/component/6.1.login.scss
> #148 高さ固定を解除

- assets/scss/mixins/_animation.scss
- assets/scss/project/11.2.header.scss
> #154 fadeIn/Out削除

- assets/scss/project/11.1.role.scss
- assets/scss/project/16.1.history.scss
- assets/tmpl/moc/user/favorite/empty/index.pug
- assets/tmpl/moc/user/favorite/index.pug
- assets/tmpl/moc/user/history/empty/index.pug
- assets/tmpl/moc/user/history/index.pug
- assets/tmpl/moc/user/mypage/index.pug
> #149 注文履歴、お気に入り商品なしのmoc用意

- assets/scss/project/16.1.history.scss
- assets/tmpl/elements/16.1.history.pug
> 16.1.1「注文履歴一覧 規格」 修正

- composer.json
> composer.jsonのnameのタイポを修正

- circle.yml
- package-lock.json
- package.json
devとmasterのcommitで差分があったので修正しました。
issue #183
> 一部commitが取り込めていないため修正

- README.md
> Update for Version 4.x.x
